version: "3.2"

services:
  portainer:
    command: -H unix:///var/run/docker.sock
    image: portainer/portainer
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`${PORTAINER_UI_DOMAIN}`)
      - traefik.http.services.portainer.loadbalancer.server.port=${PORTAINER_UI_PORT}
    networks:
      - traefik
    ports:
      - ${PORTAINER_AGENT_PORT}:8000
      - ${PORTAINER_UI_PORT}:9000

networks:
  traefik:
    external: true
