version: "3.2"

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    image: portainer/portainer
    networks:
      - portainer_agent
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_LOCAL_STORAGE_PATH}:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer.rule=Host(`${PORTAINER_UI_DOMAIN}`)
        - traefik.http.routers.portainer.entryPoints=https
        - traefik.http.routers.portainer.tls=true
        - traefik.http.routers.portainer.tls.certresolver=letsencrypt
        - traefik.http.services.portainer.loadbalancer.server.port=9000

networks:
  portainer_agent:
    driver: overlay
    attachable: true
  traefik:
    external: true
