version: "2"
services:
  portainer:
    image: portainer/portainer
    ports:
      - ${PORTAINER_AGENT_PORT}:8000
      - ${PORTAINER_UI_PORT}:9000
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data:
